title: generic-scratch-paint-new-backdrop
hero_image: images/banner.png
description: generic-scratch-paint-new-backdrop description
theme: cc-prototype 
duration: 1 
listed: false
ingredient: true
copyedit: false
interests: 
technologies: "scratch"
steps:
  - title: Paint a new backdrop
  