title: Paint a new Scratch backdrop
hero_image: images/banner.png
description: How to paint a new Scratch backdrop
theme: cc-prototype 
duration: 1 
listed: false
ingredient: true
copyedit: false
interests: 
technologies: "scratch"
steps:
  - title: Paint a new backdrop
  
