title: Paint a new backdrop
hero_image: images/banner.png
description: Scratch Paint a new backdrop
theme: cc-prototype 
duration: 1 
listed: false
ingredient: true
copyedit: false
interests: 
technologies: "scratch"
steps:
  - title: Paint a new backdrop
  